// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVnaNCZ4h6W3r9QWSvkBaFw_XjPIa8ig4',
    appId: '1:166048060729:web:ed9a309a435921791484e8',
    messagingSenderId: '166048060729',
    projectId: 'healthcare-f7e74',
    authDomain: 'healthcare-f7e74.firebaseapp.com',
    storageBucket: 'healthcare-f7e74.appspot.com',
    measurementId: 'G-SMNBW50Q96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB15FojqV658LrqJbfz3X2Nd8VON60Y3Ak',
    appId: '1:166048060729:android:4d9e1076ef01a47c1484e8',
    messagingSenderId: '166048060729',
    projectId: 'healthcare-f7e74',
    storageBucket: 'healthcare-f7e74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNoec9adav5plZhF5DcehrihJ8H6QiGEs',
    appId: '1:166048060729:ios:d0b317424e91119e1484e8',
    messagingSenderId: '166048060729',
    projectId: 'healthcare-f7e74',
    storageBucket: 'healthcare-f7e74.appspot.com',
    iosClientId: '166048060729-5gcmqn45qvre6f00mlu1vo4hr9nppd4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.scanProducts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNoec9adav5plZhF5DcehrihJ8H6QiGEs',
    appId: '1:166048060729:ios:e29537991652a27f1484e8',
    messagingSenderId: '166048060729',
    projectId: 'healthcare-f7e74',
    storageBucket: 'healthcare-f7e74.appspot.com',
    iosClientId: '166048060729-sdamo3lf0hcnt13b0g8kq1n86ik0b05r.apps.googleusercontent.com',
    iosBundleId: 'com.example.scanProducts.RunnerTests',
  );
}
